pipeline {
  agent any
  stages {
       stage("Git Revert") {
            steps {
                sh '''
                cd /home/vagrant/wordpress
                sudo git revert HEAD
                git add .
                git push git@github.com:DaryaKap/wordpress_project.git
                '''
            }
        }
    }
    post {
        success {
            withCredentials([string(credentialsId: 'tel_secret', variable: 'TOKEN'),string(credentialsId: 'tel_chat_id', variable: 'CHAT_ID')]) {
                sh """
                curl -s -X POST https://api.telegram.org/bot${TOKEN}/sendMessage -d chat_id=${CHAT_ID} -d parse_mode=markdown -d text='Report:\r
                *Project name :* ${currentBuild.projectName}\r
                *Version :* ${currentBuild.displayName}\r
                *Status :* ${currentBuild.result}'
                """
            }
        }
    }
}
