pipeline {
  agent any
  stages {
       stage("verify tooling") {
            steps {
                sh '''
                docker exec -i 5e44d35e334a /restore_backup.sh /backup/wordpress.2022-08-09_19-04-15.sql
                '''
            }
        }
    }
    post {
        success {
            withCredentials([string(credentialsId: 'tel_secret', variable: 'TOKEN'),string(credentialsId: 'tel_chat_id', variable: 'CHAT_ID')]) {
                sh """
                curl -s -X POST https://api.telegram.org/bot${TOKEN}/sendMessage -d chat_id=${CHAT_ID} -d parse_mode=markdown -d text='Report:\r
                *Project name :* ${currentBuild.projectName}\r
                *Version :* ${currentBuild.displayName}\r
                *Status :* ${currentBuild.result}'
                """
            }
        }
    }
}
