pipeline { 
 agent { 
    docker {  
            image 'mysql:8.0.27' 
   args '-u root' 
        } 
    } 
 stages {
   stage ("Install packages") { 
     steps { 
        sh ''' 
        ls -la 
        '''
      }
    }
  }
}
