services:
  db:
    # If you really want to use MySQL, uncomment the following line
    image: mysql:8.0.27
    container_name: dbmysql
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - /db_data:/var/lib/mysql
      - /backup:/backup
    restart: always
    env_file: db.env

    expose:
      - 3306
      - 33060
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - /home/vagrant/final_project/wordpress/wp_data:/var/www/html
    ports:
      - 80:80
    restart: always
    env_file: wordpress.env

volumes:
  db_data:
