pipeline {
  agent any
  stages {
    stage("verify tooling") {
      steps {
        sh '''
          docker version
          docker info
          docker compose version 
          curl --version
          jq --version
        '''
      }
    }
    stage('Start container') {
      steps {
        sh 'docker-compose -f /home/user/final_project/wordpress/docker-compose.yml up -d'
        sh 'docker-compose -f /home/user/final_project/wordpress/docker-compose.yml  ps'
      }
    }
  }
}
